services:
  db:
    image: postgres:14
    container_name: library_system_database
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:?error}
    volumes:
      - postgres_volume_data:/var/lib/postgresql/data
    ports:
      - ${DB_POSTGRES_PORT:?error}:5432
  redis:
    image: redis:6.0.7
    container_name: library_system_redis_caching
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - ${REDIS_PORT:?error}:6379
volumes:
  redis_volume_data:
  postgres_volume_data:
